### PR TITLE
File query optimizations (take 3), bugfixes

### PR DESCRIPTION
**Pull request by FredericaBernkastel**
**1.** "`getByExcludeTags`" now should be even faster than "`getByTags`". I cannot measure exactly, it's just few milliseconds, better check with CLI.

**2.** WAL checkpoint handling was broken. 
https://github.com/mserajnik/hydrusrv/blob/8c40f10d379ef327eb3bc05813c6075571b652f0/server/db/index.js#L34-L35
https://github.com/mserajnik/hydrusrv/blob/8c40f10d379ef327eb3bc05813c6075571b652f0/server/db/index.js#L48-L49
Plus, even if checkpoint was successfull, journal will persist on the disk, doubling it's size.
We'll better call it from sync, with truncate modifier.

**3.** Closed issue #12 

**4.** Closed issue #13

### CODE REVIEW

**Comment by mserajnik** [comment]
1. 👍
2. Thanks – yeah, that's wrong – it should've tried checkpointing them one after the other, not both at the same time; but to make sure we have the same thought process, are the following assumptions correct?
  - Checkpointing the content DB in hydrusrv-sync makes more sense, you are right, because hydrusrv never writes anything to that DB itself (in that case, I will add that in a new hydrusrv-sync release later today)
  - Since the authentication DB will be the only one getting checkpointed by hydrusrv, getting rid of the `DB_WAL_SIZE` comparison and just checkpointing it makes sense, since it won't grow very fast anyway
3. 👍
4. 👍

---

No objections otherwise, thanks!

**Comment by FredericaBernkastel** [comment]
I mean it was broken, because from "setCheckpointInterval" you call "checkpointIfNeeded" on both databases.
From "checkpointIfNeeded", you call "checkpoint".
And from "checkpoint", you do checkpoint on both databases.

4 checkpoints in total, which may cause weird behaviour.

**Comment by FredericaBernkastel** [comment]
>are the following assumptions correct?

Even if hydrusrv shuts down gracefully, journal files still persist on the disk. I don't know it's a bug of better-sqlite3 or what, but normally, they should be merged and deleted.

**Comment by mserajnik** [comment]
> Even if hydrusrv shuts down gracefully, journal files still persist on the disk. I don't know it's a bug of better-sqlite3 or what, but normally, they should be merged and deleted.

Yeah, I've encountered that problem when I had the checkpoint in hydrusrv-sync while I was developing it. Iirc, that was the reason I moved the checkpointing to hydrusrv and it worked there for me. Using `PRAGMA wal_checkpoint(TRUNCATE)` in hydrusrv-sync does seem to work though (the WAL file still persists but is emptied).

Unsure about this, but I'll keep an eye on it, at least I don't think it will cause issues now.

**Pull request merged**
